### ISSUE TITLE
Filter out existing charging stations

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [DavidMoraisFerreira/ChargingStations2osm#2]
Currently all charging stations from the dataset are exported into the output file.
It would be nice to be able to filter out nodes that already exist in OSM and didn't change from the previous import.

**Comment by grischard** [comment]
Maybe relevant: https://overpass-turbo.eu/s/wSm

**Comment by DavidMoraisFerreira** [comment]
Closed this issue since we use [OSM Conflator](https://github.com/mapsme/osm_conflate).
